name: Publish to NPM

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Build licia
        run: npm i && npm link && npm run build
      - name: Publish package on NPM
        working-directory: .licia/packages
        run: |
          cd licia
          npm publish
          cd ../licia-es
          npm publish
          cd ../eustia-module
          npm publish
          cd ../miniprogram-licia
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}